### ISSUE TITLE
XMLTV parsing

### ISSUE THREAD

**Issue by veso266** [Gemorroj/M3uParser#10]
Hi since this project is more a TV parser (it parses IPTV m3u playlists) then mp3 parser (parses list of mp3 files to be played) I was wondering if there are any plans on adding support for XMLTV guide parsing
recently I was playing with this: https://github.com/bcmoney/OpenRecommender/blob/master/lib/services/scraper/video/tv/xmltv/xmltv.class.php trying to parse this file: http://epg.dxing.si/xmltv/example.xml but it aphears that xmltv-class.php doesn't do anything I also found this: https://gist.github.com/azhurb/3690998 but I don't think it parses xml

Thanks for Anwsering and Best Regards

PS: in the final stage I would like to parse this: http://epg.dxing.si/download/new.xml (but its large file and I am not sure if php likes that)

**Comment by Gemorroj** [comment]
Hi.
The project focuses only on support of the format `m3u`.
`xmltv` is a separate format.
But, because `xmltv` is xml format, you can just use [SimpleXml ](https://secure.php.net/manual/en/book.simplexml.php)(example: https://secure.php.net/manual/en/simplexml.examples-basic.php).
Plans to support other formats (not only `m3u`) is not present.
